### ISSUE TITLE
How do VMs use the entropy?

### ISSUE THREAD

**Issue by adrelanos** [mirage/xentropyd#11]
Let's suppose one runs xentropy (`sudo xentropy --daemon`) in dom0.

What one has to setup in a VM to make actually make use of it?

**Comment by adrelanos** [comment]
Let's suppose one runs xentropy (`sudo xentropy --daemon`) in dom0.

What one has to setup in a VM to make actually make use of it?

**Comment by pqwy** [comment]
Depends on which kinds of VM do you have in mind. `xentropyd` is used for MirageOS VMs. It's a backend for [mirage-entropy](https://github.com/mirage/mirage-entropy).

You connect to it via a Xen console, and after the initial [handshake](https://github.com/mirage/xentropyd/blob/master/src/randomFlow.ml#L18), it starts sending data from dom0's `/dev/urandom`.

The only code to connect to `xentropyd`, request, and use the entropy is currently in mirage-entropy, so if you are talking about using it to, say, seed a Linux VM, you would need to implement a similar client from scratch. And in mirage-entropy, this code is presently disabled because some reliability features are missing on the client side. At the same time, a MirageOS VM is capable of seeding itself internally.
